server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/betca
    username: postgres
    password: postgres

miw:
  jwt:
    secret: jwt-secret
  oauth2:
    client-id: client-id
    client-secret: client-secret
    redirect-uri: http://localhost:${local.server.port}/login/oauth2/code/cliente-oidc
    issuer: http://localhost:${local.server.port}

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    oauth2RedirectUrl: http://localhost:8080/login/oauth2/code/cliente-oidc
